### ISSUE TITLE
RSTB function not working 

### ISSUE THREAD

**Issue by Amiibolad** [NiceneNerd/Wild-Bits#2]
I was able to use the program to update the rstb when i first downloaded it; the next day, the functionality to even open the rstb was gone, the open button works on the SARC side, but does nothing on the RSTB side? I've tried uninstalling and reinstalling. Nothing.

**Comment by NiceneNerd** [comment]
I can't reproduce this.

**Comment by Amiibolad** [comment]
Would you like me to provide some video evidence?

**Comment by NiceneNerd** [comment]
It's not so much evidence I need as some kind of logging. Try running it with `python -m wildbits.__init__` and recording the console output when you try to open an RSTB.

**Comment by Amiibolad** [comment]
Traceback (most recent call last):
  File "C:\Users\Owner\AppData\Local\Programs\Python\Python37\lib\site-packages\wildbits\__init__.py", line 601, in OpenRstb_Clicked
    self.rstb_hashes[int(parsed[0], 16)] = parsed[1]
IndexError: list index out of range

**Comment by Amiibolad** [comment]
I don't know if that helps, I have zero skill in this sort of thing

**Comment by NiceneNerd** [comment]
Oh, I see. Something got messed up in your `added_hashes` file, and I really need something to account for that possibility. I'll work on a fix; in the meantime delete the file `C:\Users\Owner\AppData\Local\Programs\Python\Python37\lib\site-packages\wildbits\added_hashes`.

**Comment by Amiibolad** [comment]
Okies, will do :)

**Comment by Amiibolad** [comment]
Opens :) thanks you
