### ISSUE TITLE
No longer estimating resource size for .bfres

### ISSUE THREAD

**Issue by Amiibolad** [NiceneNerd/Wild-Bits#5]
Hi, 

I recently updated to the latest version and I've found that it now lacks the ability to detect the resource size from .bfres. I found that in the past the estimation was quite good but having it do nothing is going to make using wildbits nearly impossible. Is this an error or a feature and if it is a feature, how can I roll my install back?

**Comment by Amiibolad** [comment]
No response to this? Thanks.

**Comment by Amiibolad** [comment]
I will also add that the update from folder option does nothing, the rstb editor throws random amounts that will no where near cover the memory cost of basic sbactorpacks, whole app seems to have been massively downgraded.

**Comment by NiceneNerd** [comment]
So, BFRES estimates are still a feature, but a change in the `botw-utils` dependency broke it. Easy fix, pushed now.

Update from folder was broken by a typo, also fixed.

No idea what you mean about the RSTB editor. I can't replicate it or find any problems. It's giving me the exact same output as `rstbtool` for actor packs.
